/**
 * Registry of the published guidelines and patient resources the decision-support rules
 * are built on. Every rule in src/cds cites one or more ids from this registry, so a
 * clinician can trace any recommendation back to its source.
 *
 * Guideline bodies publish documents (journal articles, PDFs, web pages), not data feeds,
 * so the rules encode their thresholds by hand. When a source is revised, update its entry
 * here (including `reviewedOn`), then update the rules that cite it (search src/cds for its id).
 */

export type GuidelineKind = 'guideline' | 'consensus' | 'diagnostic-criteria' | 'safety' | 'research' | 'patient-education';

export interface GuidelineSource {
  id: string;
  organization: string;
  title: string;
  year: number;
  kind: GuidelineKind;
  url: string;
  citation?: string;
  /** What Aura takes from this document. */
  usedFor: string[];
  /** Date the Aura maintainers last checked the entry against the source. */
  reviewedOn: string;
  /** Set when a newer document replaces this one for some purposes. */
  supersededBy?: string;
  note?: string;
}

export const GUIDELINES: GuidelineSource[] = [
  {
    id: 'aan-ahs-2026-prevention',
    organization: 'American Academy of Neurology & American Headache Society',
    title: 'Pharmacologic Treatment for Migraine Prevention in Adults',
    year: 2026,
    kind: 'guideline',
    url: 'https://doi.org/10.1212/WNL.0000000000214881',
    citation: 'Neurology 2026;107(7):e214881. Also published in Headache.',
    usedFor: [
      'Offer prevention at ≥4 migraine days or ≥4 moderate-to-severe headache days per month, or when migraine interferes with work or daily activities',
      'Counsel people of childbearing potential on fetal risk; avoid valproate and topiramate if possible (Level A)',
      'Topiramate above 200 mg/day can make hormonal contraception less effective',
    ],
    reviewedOn: '2026-10-09',
    note: 'Replaces the 2012 AAN/AHS pharmacologic prevention guideline. The full text is the reference for drug-level evidence grades.',
  },
  {
    id: 'ahs-2024-cgrp',
    organization: 'American Headache Society',
    title: 'Calcitonin gene-related peptide-targeting therapies are a first-line option for the prevention of migraine: An AHS position statement update',
    year: 2024,
    kind: 'consensus',
    url: 'https://doi.org/10.1111/head.14692',
    citation: 'Charles AC, et al. Headache 2024;64(4):333-341.',
    usedFor: ['CGRP monoclonal antibodies and gepants may be started without first failing older preventives'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'ahs-2021-consensus',
    organization: 'American Headache Society',
    title: 'The American Headache Society Consensus Statement: Update on integrating new migraine treatments into clinical practice',
    year: 2021,
    kind: 'consensus',
    url: 'https://doi.org/10.1111/head.14153',
    citation: 'Ailani J, et al. Headache 2021;61(7):1021-1039.',
    usedFor: [
      'Acute treatment goals: freedom from pain or the most bothersome symptom within 2 hours',
      'Gepants or lasmiditan when ≥2 oral triptans have not worked or are contraindicated',
      'Limit acute medication days to avoid medication overuse',
      'Treat early in the attack, while pain is still mild',
    ],
    reviewedOn: '2026-10-09',
    supersededBy: 'aan-ahs-2026-prevention',
    note: 'The prevention thresholds in this statement have been superseded by the 2026 AAN/AHS guideline. The acute-treatment guidance still applies.',
  },
  {
    id: 'ichd-3',
    organization: 'International Headache Society',
    title: 'International Classification of Headache Disorders, 3rd edition (ICHD-3)',
    year: 2018,
    kind: 'diagnostic-criteria',
    url: 'https://ichd-3.org/',
    citation: 'Cephalalgia 2018;38(1):1-211.',
    usedFor: [
      'Chronic migraine: headache on ≥15 days/month, with ≥8 of those days having migraine features, for >3 months',
      'Status migrainosus: a debilitating attack lasting >72 hours',
      'Typical aura lasts 5–60 minutes',
      'Menstrual migraine: attacks starting from 2 days before to 3 days after the start of menstruation in ≥2 of 3 cycles',
    ],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'ichd-3-moh',
    organization: 'International Headache Society',
    title: 'ICHD-3 §8.2 Medication-overuse headache',
    year: 2018,
    kind: 'diagnostic-criteria',
    url: 'https://ichd-3.org/8-headache-attributed-to-a-substance-or-its-withdrawal/8-2-medication-overuse-headache-moh/',
    usedFor: [
      'Overuse thresholds: triptans, ergots, opioids, combination analgesics or multiple classes on ≥10 days/month; simple analgesics and NSAIDs on ≥15 days/month, for >3 months',
    ],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'snnoop10',
    organization: 'Neurology (peer-reviewed review)',
    title: 'Red and orange flags for secondary headaches in clinical practice: SNNOOP10 list',
    year: 2019,
    kind: 'safety',
    url: 'https://doi.org/10.1212/WNL.0000000000006697',
    citation: 'Do TP, et al. Neurology 2019;92(3):134-144.',
    usedFor: ['Red-flag screening on every attack log'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'aan-ahs-2012-complementary',
    organization: 'American Academy of Neurology & American Headache Society',
    title: 'Evidence-based guideline update: NSAIDs and other complementary treatments for episodic migraine prevention in adults',
    year: 2012,
    kind: 'guideline',
    url: 'https://doi.org/10.1212/WNL.0b013e3182535d0c',
    citation: 'Holland S, et al. Neurology 2012;78(17):1346-1353.',
    usedFor: ['Evidence levels and doses for magnesium, riboflavin, feverfew, CoQ10 and butterbur'],
    reviewedOn: '2026-10-09',
    note: 'The AAN withdrew its butterbur recommendation in 2015 over liver-safety concerns. The 2026 guideline covers only prescription medicines, so this remains the reference for supplements.',
  },
  {
    id: 'nice-cg150',
    organization: 'National Institute for Health and Care Excellence (UK)',
    title: 'Headaches in over 12s: diagnosis and management (CG150)',
    year: 2012,
    kind: 'guideline',
    url: 'https://www.nice.org.uk/guidance/cg150',
    usedFor: ['Headache diaries; riboflavin 400 mg/day; managing medication overuse by stopping the overused drug'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'ehf-2022-cgrp',
    organization: 'European Headache Federation',
    title: 'European Headache Federation guideline on the use of monoclonal antibodies targeting the CGRP pathway for migraine prevention – 2022 update',
    year: 2022,
    kind: 'guideline',
    url: 'https://doi.org/10.1186/s10194-022-01431-x',
    citation: 'Sacco S, et al. J Headache Pain 2022;23:67.',
    usedFor: ['European perspective on CGRP antibody use, including in medication overuse'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'cdc-us-mec',
    organization: 'U.S. Centers for Disease Control and Prevention',
    title: 'U.S. Medical Eligibility Criteria for Contraceptive Use (US MEC)',
    year: 2024,
    kind: 'safety',
    url: 'https://www.cdc.gov/contraception/hcp/usmec/',
    usedFor: ['Combined hormonal contraception is category 4 (unacceptable risk) in migraine with aura'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'ahs-2010-serotonin',
    organization: 'American Headache Society',
    title: 'The FDA alert on serotonin syndrome with use of triptans combined with SSRIs or SNRIs: AHS position paper',
    year: 2010,
    kind: 'safety',
    url: 'https://doi.org/10.1111/j.1526-4610.2010.01691.x',
    citation: 'Evans RW, et al. Headache 2010;50(6):1089-1099.',
    usedFor: ['Triptans with SSRIs/SNRIs: serotonin syndrome risk is low, so no need to avoid the combination; know the warning signs'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'kelman-2007-triggers',
    organization: 'Cephalalgia (peer-reviewed study)',
    title: 'The triggers or precipitants of the acute migraine attack',
    year: 2007,
    kind: 'research',
    url: 'https://doi.org/10.1111/j.1468-2982.2007.01303.x',
    citation: 'Kelman L. Cephalalgia 2007;27(5):394-402.',
    usedFor: ['How common each trigger is among people with migraine (stress 80%, hormones 65%, not eating 57%, …), used to set the starting weights of the risk model'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'pellegrino-2018-perceived',
    organization: 'Cephalalgia (meta-analysis)',
    title: 'Perceived triggers of primary headache disorders: A meta-analysis',
    year: 2018,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28825314/',
    citation: 'Pellegrino ABW, et al. Cephalalgia 2018;38(6):1188-1198.',
    usedFor: ['Perceived triggers are common but often not confirmed prospectively, which is why the model lets personal data override starting beliefs'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'macgregor-2004',
    organization: 'Neurology (prospective diary study)',
    title: 'Prevalence of migraine on each day of the natural menstrual cycle',
    year: 2004,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/15277635/',
    citation: 'MacGregor EA, et al. Neurology 2004;63(2):351-353.',
    usedFor: ['Migraine 1.7× as likely in the 2 days before menses and >2× on days 1–3'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'lipton-2014-letdown',
    organization: 'Neurology (prospective e-diary)',
    title: 'Reduction in perceived stress as a migraine trigger',
    year: 2014,
    kind: 'research',
    url: 'https://stacks.cdc.gov/view/cdc/200156',
    citation: 'Lipton RB, et al. Neurology 2014.',
    usedFor: ['Stress let-down OR 1.5–1.9 over the next 6–18 h'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'holsteen-2020',
    organization: 'Headache (prospective diary)',
    title: 'Prospective diary study of daily predictors of migraine attacks',
    year: 2020,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/33022773/',
    citation: 'Holsteen KK, et al. Headache 2020. doi:10.1111/head.13960',
    usedFor: ['Stress, caffeine reduction and self-predicted risk as predictors; within-person C-statistic 0.56'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'lateef-2024-emotions',
    organization: 'Neurology (ecological momentary assessment)',
    title: 'Ecological momentary assessment of sleep, energy, mood and stress before headache onset',
    year: 2024,
    kind: 'research',
    url: 'https://www.neurology.org/doi/10.1212/WNL.0000000000208102',
    citation: 'Lateef T, et al. Neurology 2024.',
    usedFor: ['Anger/negative mood not significant after adjustment'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'mosek-1995-fasting',
    organization: 'Peer-reviewed cohort study',
    title: 'Yom Kippur headache',
    year: 1995,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/7501139/',
    citation: 'Mosek A, Korczyn AD. 1995.',
    usedFor: ['Headache in 39% of fasters vs 7% of non-fasters'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'vives-mestres-2022-alcohol',
    organization: 'Headache (prospective app cohort)',
    title: 'Alcohol as a trigger of migraine attacks',
    year: 2022,
    kind: 'research',
    url: 'https://doi.org/10.1111/head.14428',
    citation: 'Vives-Mestres M, et al. Headache 2022.',
    usedFor: ['Alcohol OR 1.01 (0.91–1.11) for next-day migraine'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'mostofsky-2019-caffeine',
    organization: 'American Journal of Medicine (case-crossover)',
    title: 'Prospective cohort study of caffeinated beverage intake as a potential trigger of headaches among migraineurs',
    year: 2019,
    kind: 'research',
    url: 'https://www.sciencedirect.com/science/article/abs/pii/S0002934319302104',
    citation: 'Mostofsky E, et al. Am J Med 2019;132(8):984-991.',
    usedFor: ['Risk rises at ≥3 caffeinated servings/day'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'mukamal-2009-weather',
    organization: 'Neurology (case-crossover, 7,054 ED visits)',
    title: 'Weather and air pollution as triggers of severe headaches',
    year: 2009,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/19273827/',
    citation: 'Mukamal KJ, et al. Neurology 2009;72(10):922-927.',
    usedFor: ['OR 1.075 per 5 °C temperature rise'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'hougaard-2013-provocation',
    organization: 'Neurology (provocation study)',
    title: 'Provocation of migraine with aura using natural trigger factors',
    year: 2013,
    kind: 'research',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3620071/',
    citation: 'Hougaard A, et al. Neurology 2013. doi:10.1212/WNL.0b013e31827f0f10',
    usedFor: ['Light and exercise rarely provoked attacks in the lab'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'giffin-2003-premonitory',
    organization: 'Neurology (prospective e-diary)',
    title: 'Premonitory symptoms in migraine: an electronic diary study',
    year: 2003,
    kind: 'research',
    url: 'https://pubmed.ncbi.nlm.nih.gov/12654956/',
    citation: 'Giffin NJ, et al. Neurology 2003;60(6):935-940.',
    usedFor: ['72% of premonitory symptoms were followed by a headache'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'amf-moh',
    organization: 'American Migraine Foundation',
    title: 'Medication Overuse Headache (patient guide)',
    year: 2024,
    kind: 'patient-education',
    url: 'https://americanmigrainefoundation.org/wp-content/uploads/2024/09/2203_AMF_Medication_Overuse_V5_Digital.pdf',
    usedFor: ['Patient explanation of medication overuse and how to break the cycle'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'amf-library',
    organization: 'American Migraine Foundation',
    title: 'Resource Library',
    year: 2026,
    kind: 'patient-education',
    url: 'https://americanmigrainefoundation.org/resource-library/',
    usedFor: ['Patient-facing material on triggers, acute and preventive treatment, and lifestyle'],
    reviewedOn: '2026-10-09',
  },
  {
    id: 'ahs-patient-guides',
    organization: 'American Headache Society',
    title: 'Patient guides (First Contact program)',
    year: 2026,
    kind: 'patient-education',
    url: 'https://americanheadachesociety.org/resources/primary-care/patient-guides',
    usedFor: ['Printable guides on episodic vs chronic migraine and medication overuse'],
    reviewedOn: '2026-10-09',
  },
];

export const guidelineById = (id: string): GuidelineSource | undefined => GUIDELINES.find((g) => g.id === id);
